import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import NavLink from "@/components/navbar/NavLink";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${hindSiliguri.className}  h-full antialiased`}>
      <body className="bg-[#F0F5F0]">
        <div className="max-w-7xl mx-auto p-8">
          <Navbar></Navbar>
        </div>
        <NavLink></NavLink>
        <Marquee></Marquee>

        <div className="max-w-7xl mx-auto p-8">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
